workers:
  vite:
    # Windows i Linux: npm spustí vite
    cmd: ['npm', 'run', 'dev', '--', '--host', '127.0.0.1', '--port', '5173']
    # (volitelné) restart, když změníš config:
    watch: ['vite.config.ts', 'package.json']

  messenger:
    cmd: ['symfony', 'console', 'messenger:consume', 'async', '-vv']
    watch: ['config', 'src', 'templates', 'vendor']